services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    volumes:
      - ./config:/config
      - ./cache:/cache
      - type: bind
        source: /home/duc/Videos
        target: /media
      - type: bind
        source: /home/duc/Music
        target: /media2
    ports:
      - 8096:8096    
    restart: 'unless-stopped'