---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

title: My Awesome Homepage
background:
  image: https://r4.wallpaperflare.com/wallpaper/855/698/460/science-fiction-cityscape-futuristic-star-wars-wallpaper-9daca38453a13192514bb1a8d3a26fc5.jpg
  blur: "xl"
  saturate: 100
  brightness: 100
  opacity: 100
theme: dark
layout:
  Media:
    style: row
    columns: 4
  My Second Group:
    style: row
    columns: 4  
  My Third Group:
    style: row
    columns: 4        
providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
